resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/button-card.js
    type: module
  - url: /local/bignumber-card.js
    type: module
  - url: /local/calendar-card.js
    type: module
  - url: /local/svg-card.js?v=0.189
    type: module
  - url: https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.5.1/snap.svg-min.js
    type: js

name: Home
views:
- icon: mdi:home
  title: Lights
  cards:
  - type: entities
    title: Lights
    entities:
    - light.umbrella_led
    - light.playroom_lamp
    - light.kitchen_can_lights
    - light.living_room_chandelier
    - light.livingroom_can_lights
    - light.office_led
    - light.office_light
    - light.pantry_led
    - switch.back_porch_light
    - switch.front_porch_light
    - switch.garage_outside_light
    - switch.kitchen_pendant_lights
    - switch.master_bedroom_light
    - switch.playroom_can_lights
    - switch.playroom_fan_light
    - switch.side_entry_porch_light
    - switch.stair_light
  - type: entities
    title: Fans
    entities:
    - fan.playroom_fan_level
    - fan.master_bedroom_fan_level
    - switch.office_fan
  - type: vertical-stack
    cards:
      - type: glance
        title: Locks
        entities:
        - lock.back_door
        - lock.side_entry
        - lock.garage_entry
        - lock.front_door
      - type: glance
        title: Exterior Entrances
        entities:
        - sensor.back_door_state
        - sensor.front_door_state
        - sensor.side_door_state
      - type: glance
        title: Gates
        entities:
        - sensor.south_gate_state
        - sensor.north_gate_state
- icon: mdi:silverware-fork-knife
  cards: 
  - type: "custom:calendar-card"
    name: "Menu"
    showProgressBar: false
    entities: 
      - calendar.meal_plan
- icon: mdi:cctv
  cards:
  - type: picture-entity
    entity: camera.front_door_live
  - type: picture-entity
    entity: camera.back_door_live
  - type: picture-entity
    entity: camera.side_entry_live
  - type: picture-entity
    entity: camera.girls_room
- icon: mdi:television
  cards:
  - type: media-control
    entity: media_player.playroom_tv
  - type: media-control
    entity: media_player.office_tv
  - type: media-control
    entity: media_player.living_room_tv
    #- icon: mdi:pine-tree
    #  cards:
    #  - type: entities
    #    title: Inside Lights
    #    entities:
    #    - switch.christmas_tree
    #    - switch.mantle_garland_lights
    #    - switch.built_in_left
    #    - switch.built_in_right
    #    - switch.fireplace_trees
    #  - type: "vertical-stack"
    #    cards:
    #      - type: horizontal-stack
    #        cards:
    #          - type: "custom:button-card"
    #            entity: light.backyard_tree_led
    #            name: Backyard Tree
    #            color: auto
    #            icon: mdi:pine-tree
    #            action: more_info
    #          - type: "custom:button-card"
    #            entity: input_boolean.option_backyard_tree_rotate_pattern
    #            name: Pattern Rotation
    #            icon: mdi:rotate-3d
    #            color: rgb(0, 200, 0)
    #          - type: "custom:bignumber-card"
    #            entity: sensor.backyard_tree_current_pattern
    #            title: PATTERN
    #            scale: '33px'
    #      - type: horizontal-stack
    #        cards:
    #          - type: "custom:button-card"
    #            entity: light.backyard_tree_led
    #            show_state: true
    #          - type: "custom:button-card"
    #            entity: input_boolean.option_backyard_tree_rotate_pattern
    #            show_state: true
    #          - type: "custom:button-card"
    #            color_type: card
    #            color: rgb(255, 255, 255)
    #            icon: mdi:chevron-double-right
    #            action: service
    #            size: '20px'
    #            service:
    #              domain: mqtt
    #              action: publish
    #              data:
    #                topic: "led/tree/patternAdjust"
    #                payload: "1"
#      - type: horizontal-stack
#        cards:
#          - type: entities
#            entities:
#            - input_number.option_backyard_tree_single_pixel
#          - type: "custom:bignumber-card"
#            entity: input_number.option_backyard_tree_single_pixel

           
- icon: mdi:account-location
  cards:
  - type: entities
    title: Locations
    entities:
    - device_tracker.matt_iphone
    - device_tracker.alydia_iphone
  - type: entities
    title: Bed Occupancy
    entities:
    - sensor.bed_matt
    - sensor.bed_alydia
    - sensor.bed_both
- icon: mdi:battery
  cards: 
  - type: entities
    title: Battery Levels
    entities:
    - sensor.front_door_sensor_battery
    - sensor.front_door_deadbolt_battery
    - sensor.back_door_sensor_battery
    - sensor.back_door_deadbolt_battery
    - sensor.side_door_sensor_battery
    - sensor.side_door_deadbolt_battery
    - sensor.garage_door_deadbolt_battery
    - sensor.kitchen_leak_sensor_battery
    - sensor.master_bath_leak_sensor_battery
    - sensor.north_gate_sensor_battery
    - sensor.south_gate_sensor_battery

- icon: mdi:settings
  cards:
  - type: entities
    title: House Modes
    entities:
    - input_boolean.away_mode
    - input_boolean.guest_mode
    - input_boolean.sleep_mode
    - input_boolean.extended_away_mode
  - type: entities
    title: Master Bedroom Settings
    entities:
    - input_boolean.flag_fan_on_when_bed_occupied
    - input_boolean.flag_fan_on_at_bedtime
    - input_select.option_fan_speed_at_bedtime
  - type: entities
    title: Bedtimes
    entities:
    - input_datetime.option_girls_weekday_bedtime
    - input_datetime.option_girls_weekend_bedtime
- icon: mdi:floor-plan
  panel: false
  cards:
          #  - type: "custom:svg-card"
          #svg_url: "/local/svg/test.svg"
          #title: "Downstairs"
  - type: "custom:svg-card"
    svg_url: "/local/svg/test2.svg"
    title: "Upstairs"
